sdk/ic_vetkd_sdk_encrypted_maps_example/src/index.test.ts
Fixes the currently failing `encrypted-maps-example` workflow.
=> chore: fix SDK CI

.github/workflows/key-manager-example.yml, package-lock.json, sdk/ic_vetkd_sdk_key_manager/package.json
Clean up the key manager's package.json:
* Add missing `@dfinity/principal`
* Downgrade `typescript` to dev-dependency
* Remove ts-node dependency, as it seems unused
* Remove things related to babel because they are unused
* Remove things related to jest and testing, because currently there are no tests in this module
* Remove things related to tslint and linting, because tslint [has been deprecated](https://medium.com/palantir/tslint-in-2019-1a144c2317a9) as of 2019
The typescript package is outdated, but this will be fixed in separate PRs so as not to pollute this PR here.
```
sdk/ic_vetkd_sdk_key_manager/ [main] npx npm-check
@dfinity/agent             😕  NOTUSED?  Still using @dfinity/agent?
Depcheck did not find code similar to require('@dfinity/agent') or import from …
```
=> chore: CRP-2724 cleanup key manager's package.json

.github/workflows/encrypted-maps-example.yml, package-lock.json, sdk/ic_vetkd_sdk_encrypted_maps/package.json, sdk/ic_vetkd_sdk_encrypted_maps/src/index.ts
```
sdk/ic_vetkd_sdk_encrypted_maps/ [main*] npx npm-check
typescript                 😍  UPDATE!   Your local install is out of date. https://www.typescriptlang.org/
npm install typescript@5.8.2 --save to go from 5.7.3 to 5.8.2
@dfinity/agent             😕  NOTUSED?  Still using @dfinity/agent?
Depcheck did not find code similar to require('@dfinity/agent') or import from '@dfinity/agent'.
Check your code before removing as depcheck isn't able to foresee all ways dependencies can be used.
Use rc file options to remove unused check, but still monitor for outdated version:
.npmcheckrc {"depcheck": {"ignoreMatches": ["@dfinity/agent"]}}
Use --skip-unused to skip this check.
To remove this package: npm uninstall @dfinity/agent --save
@babel/preset-env          😎  PATCH UP  Patch update …
```
=> chore: CRP-2724 fix unused and missing dependencies in encrypted maps SDK

examples/password_manager/deploy_locally.sh, examples/password_manager/frontend/package.json, examples/password_manager/frontend/vite.config.js, examples/password_manager_with_metadata/deploy_locally.sh, examples/password_manager_with_metadata/frontend/package-lock.json, examples/password_manager_with_metadata/frontend/package.json, examples/password_manager_with_metadata/frontend/vite.config.js, package-lock.json
* Write dfx environment variables to an `.env` file.
* Pass the environment variables via `vite-plugin-environment`.
=> chore: CRP-2732 fix `npm run dev`

package-lock.json, sdk/ic_vetkd_sdk_key_manager_example/babel.config.js, sdk/ic_vetkd_sdk_key_manager_example/package.json, sdk/ic_vetkd_sdk_key_manager_example/src/index.ts
```
sdk/ic_vetkd_sdk_key_manager_example/ [main*] npx npm-check
@types/node                   😍  UPDATE!   Your local install is out of date. https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node
npm install @types/node@22.13.10 --save to go from 22.13.0 to 22.13.10
vite-plugin-top-level-await   😍  UPDATE!   Your local install is out of date. https://github.com/Menci/vite-plugin-top-level-await#readme
npm install vite-plugin-top-level-await@1.5.0 --save to go from 1.4.4 to 1.5.0
@babel/preset-env             😎  PATCH UP  Patch update available. https://babel.dev/docs/en/next/babel-preset-env
npm install @babel/preset-env@7.26.9 --save-dev to go from 7.26.0 to 7.26.9
@babel/register               😕  NOTUSED?  Still using @babel/register?
Depcheck did not find code …
```
=> chore: CRP-2724 fix dependencies in key manager SDK example

.github/workflows/examples-password-manager.yml, package-lock.json, sdk/ic_vetkd_sdk_encrypted_maps_example/babel.config.js, sdk/ic_vetkd_sdk_encrypted_maps_example/package.json
```
sdk/ic_vetkd_sdk_encrypted_maps_example/ [main*] npx npm-check
idb-keyval                    😕  NOTUSED?  Still using idb-keyval?
Depcheck did not find code similar to require('idb-keyval') or import from 'idb-keyval'.
Check your code before removing as depcheck isn't able to foresee all ways dependencies can be used.
Use rc file options to remove unused check, but still monitor for outdated version:
.npmcheckrc {"depcheck": {"ignoreMatches": ["idb-keyval"]}}
Use --skip-unused to skip this check.
To remove this package: npm uninstall idb-keyval --save
vite-plugin-top-level-await   😍  UPDATE!   Your local install is out of date. https://github.com/Menci/vite-plugin-top-level-await#readme
npm install vite-plugin-top-level-await@1.5.0 --save to go from 1.4.4 to 1.5.0
@babel/preset-env …
```
=> chore: CRP-2724 fix dependencies in encrypted maps SDK example

.github/workflows/cdk.yml, .github/workflows/encrypted-maps-example.yml, .github/workflows/examples-password-manager-with-metadata.yml, .github/workflows/examples-password-manager.yml, .github/workflows/key-manager-example.yml
The ubuntu-20.04 image is deprecated and will end of life April 1st
(https://github.com/actions/runner-images/issues/11101)
=> Use ubuntu-24.04 image for CI

examples/password_manager/frontend/package.json, package-lock.json
Cleanup dependencies in password manager example. There are a few dependencies that npm-check reports as unused, but they all seem used via svelte.
```
examples/password_manager/frontend/ [main] npx npm-check              
@sveltejs/vite-plugin-svelte   😎  MAJOR UP  Major update available. https://github.com/sveltejs/vite-plugin-svelte#readme
npm install @sveltejs/vite-plugin-svelte@5.0.3 --save to go from 3.0.2 to 5.0.3
@tailwindcss/postcss           😍  UPDATE!   Your local install is out of date. https://tailwindcss.com
npm install @tailwindcss/postcss@4.0.15 --save to go from 4.0.6 to 4.0.15
😕  NOTUSED?  Still using @tailwindcss/postcss?
Depcheck did not find code similar to require('@tailwindcss/postcss') or import from '@tailwindcss/postcss'.
Check your code before removing as …
```
=> chore: CRP-2724 fix dependencies in password manager example

.github/workflows/cdk.yml, .github/workflows/encrypted-maps-example.yml, .github/workflows/examples-password-manager-with-metadata.yml, .github/workflows/examples-password-manager.yml, .github/workflows/key-manager-example.yml, .github/workflows/sdk_encrypted_maps.yml, .github/workflows/sdk_key_manager.yml, .github/workflows/sdk_utils.yml, package-lock.json, package.json
Because of the typo the `password_manager_with_metadata_frontend` package was compiled in its own workspace, causing it to include many dependencies twice (we don't use explicit deduplication in `vite` in the `examples`) .
The change in the compiled size is `1028.35kb / gzip: 267.23kb -> 493.31kb / gzip: 159.32kb`.
=> fix: typo in a package name

examples/password_manager/frontend/package.json, examples/password_manager/frontend/vite.config.js, examples/password_manager_with_metadata/frontend/package-lock.json, examples/password_manager_with_metadata/frontend/package.json, examples/password_manager_with_metadata/frontend/vite.config.js, package-lock.json, sdk/ic_vetkd_sdk_encrypted_maps_example/package.json, sdk/ic_vetkd_sdk_encrypted_maps_example/vite.config.ts, sdk/ic_vetkd_sdk_key_manager/package.json, sdk/ic_vetkd_sdk_key_manager/src/index.ts, sdk/ic_vetkd_sdk_key_manager_example/package.json, sdk/ic_vetkd_sdk_key_manager_example/vite.config.ts
There were a few artifact plugins remaining from when we used WASM-based utils. They are removed in this PR, since they are not needed anymore.
=> chore: remove WASM plugins

cdk/encrypted_maps/src/lib.rs, cdk/encrypted_maps/tests/tests.rs, cdk/encrypted_maps_example/src/lib.rs, cdk/key_manager/src/lib.rs, cdk/key_manager/tests/tests.rs, cdk/key_manager_example/src/lib.rs, cdk/types/src/lib.rs, examples/password_manager_with_metadata/backend/src/lib.rs
Improves flexibility of access control by adding an `AccessControl` trait, which allows to construct custom access control rights, e.g., with a time delay for access or more fine-grained access rights. Also enforces that the caller must satisfy the condition of  `can_get_user_rights()` with `AccessRights::ReadWriteManage` (previously read rights sufficed) to retrieve other users' rights in the `AccessRights` implementation.
=> feat: CRP-2759 access control trait

frontend/ic_vetkeys/src/utils/utils.ts
The Rust library uses the name `header` for this parameter, which more accurately captures what the value is, and it's best if the Rust and TS libraries are consistent whenever possible.
=> Address an informational finding from the internal security review

frontend/ic_vetkeys/src/utils/utils.test.ts, frontend/ic_vetkeys/src/utils/utils.ts
This more clearly captures the meaning of the parameter.
=> chore(crypto): CRP-2788 Use identity instead of derivation_id in IBE encryption

examples/basic_ibe/frontend/package.json, examples/basic_ibe/frontend/src/main.ts, examples/basic_timelock_ibe/frontend/package.json, examples/basic_timelock_ibe/frontend/src/main.ts, examples/password_manager/frontend/package.json, examples/password_manager/frontend/src/components/EditPassword.svelte, examples/password_manager/frontend/src/components/SharingEditor.svelte, examples/password_manager/frontend/src/components/Vault.svelte, examples/password_manager/frontend/src/lib/encrypted_maps.ts, examples/password_manager/frontend/src/lib/vault.ts, examples/password_manager/frontend/src/store/auth.ts, examples/password_manager/frontend/src/store/vaults.ts, examples/password_manager_with_metadata/frontend/package.json, examples/password_manager_with_metadata/frontend/src/components/EditPassword.svelte, examples/password_manager_with_metadata/frontend/src/components/SharingEditor.svelte, examples/password_manager_with_metadata/frontend/src/components/Vault.svelte, examples/password_manager_with_metadata/frontend/src/lib/encrypted_maps.ts, examples/password_manager_with_metadata/frontend/src/lib/password_manager.ts, examples/password_manager_with_metadata/frontend/src/lib/vault.ts, examples/password_manager_with_metadata/frontend/src/store/vaults.ts, frontend/ic_vetkeys/eslint.config.mjs, frontend/ic_vetkeys/package.json, frontend/ic_vetkeys/src/encrypted_maps/encrypted_maps.ts, frontend/ic_vetkeys/src/key_manager/key_manager.ts, package-lock.json
- Changed the name of the package to `@dfinity/vetkeys`. (Having `ic_` prefix would be unexpected given that no other package in the `@dfinity` scope has such a prefix and they all are about IC.)
- Added some metadata like keywords, URLs, etc. to `package.json`.
- As a side-effect of looking at it, fixed the `coverage` script, since it requires canister deployment, and added an ignore to eslint for coverage.
=> chore: adapt frontend library `package.json` to be better suitable for publishing

.github/workflows/frontend.yml, frontend/ic_vetkeys/src/encrypted_maps/encrypted_maps_canister.test.ts, frontend/ic_vetkeys/src/key_manager/key_manager_canister.test.ts, package-lock.json
The workflow dependency is due to the frontend tests being dependent on backend canisters.
=> chore: fix ci by fixing two failing tests and add a workflow dependency

examples/basic_timelock_ibe/frontend/src/main.ts
Fixes the logout in the secret bid auction example, which is broken. In particular, after a logout and re-login, calls to the backend are still made with the old identity.
At the same time, the PR also
* improves the example name on the main page
* adds a code snipped that makes `npm run dev` work (which didn't work before)
* reverses the order of the open and closes lots as they are displayed in the frontend, so that the most recent lots are on top
=> fix: fix broken logout in secret bid auction example

frontend/ic_vetkeys/src/utils/utils.test.ts, frontend/ic_vetkeys/src/utils/utils.ts
Makes life a little easier for end users who might want to for example verify a VRF output
=> feat: Export a function for verifying BLS signatures from TS utils

.github/workflows/publish-frontend.yml, frontend/ic_vetkeys/package.json
Seems the default setting for publishing packages is "restricted". This PR changes it to "public".
This PR also fixes the git URL in `package.json`.
=> ci: CRP-2795 fix publish frontend workflow by making the package public

examples/basic_ibe/backend/src/lib.rs, examples/basic_ibe/frontend/src/main.ts, examples/basic_timelock_ibe/backend/src/lib.rs, examples/basic_timelock_ibe/frontend/src/main.ts
- Fixed Problem 1: In some cases `agentOptions` were not passed down to the actor creation function if deploying the frontend to mainnet.
- Fixed Problem 2: In some cases the key name that was set on canister initialization was ignored and instead `"dfx_test_key"` was always used.
=> chore: in examples fix incorrect handling of some key ids and mainnet frontend configuration

examples/basic_timelock_ibe/frontend/src/main.ts, package-lock.json
We reversed the lots based on their timestamp but used non-inverted indexing. This means that we displayed bid information as if the lots would not be reversed.
(This did not affect the correctness of the submitted bid AFAICT because that didn't use the wrong index variable.)
=> fix(basic_timelock_ibe): frontend bug in displaying bids

README.md, backend/mo/ic_vetkeys/src/encrypted_maps/EncryptedMaps.mo, backend/mo/ic_vetkeys/src/key_manager/KeyManager.mo, backend/rs/ic_vetkeys/src/encrypted_maps/mod.rs, backend/rs/ic_vetkeys/src/key_manager/mod.rs, examples/basic_ibe/README.md, examples/basic_timelock_ibe/README.md, frontend/ic_vetkeys/package.json
Updates the link to the developer docs from the old to the new format.
A redirect is currently in place that makes the old URL work seamlessly, but at some point the redirect might be removed.
=> chore: update developer docs link

examples/encrypted_notes_dapp_vetkd/README.md
Follows the structure as in the other example readmes (components -> {backend, frontend}).
=> docs: CRP-2830 mention `npm run dev` for the encrypted notes dapp

backend/rs/ic_vetkeys/src/utils/mod.rs, frontend/ic_vetkeys/src/utils/utils.ts
Makes the unit, namely bytes, explicit in the documentation of the helper functions to determine IBE ciphertext/plaintext size explicit.
=> chore(CRP-2787): make unit in IBE ciphertext/plaintext size helpers explicit

examples/encrypted_notes_dapp_vetkd/rust/backend/src/lib.rs
Prevent NEXT_NOTE_ID to wrap around by using a checked addition instead of an unchecked one. If the checked addition fails, then creating a new note simply fails, making the approach safe so that no data is lost.
The overflow issue does not affect [the respective Motoko code](https://github.com/dfinity/vetkeys/blob/main/examples/encrypted_notes_dapp_vetkd/motoko/backend/main.mo#L135), because `nextNoteId` is of type `Nat` which has [infinite precision](https://internetcomputer.org/docs/motoko/base/Nat).
=> fix(SECFIND-513): prevent NEXT_NOTE_ID to wrap around

examples/encrypted_notes_dapp_vetkd/frontend/src/components/DisclaimerCopy.svelte, examples/password_manager/frontend/src/components/DisclaimerCopy.svelte, examples/password_manager_with_metadata/frontend/src/components/DisclaimerCopy.svelte
The disclaimer text sounds like the canister is deployed on mainnet or relies on some other backend canister that we control. Remove the sentence that causes this.
=> chore: improve disclaimer text

.github/workflows/examples-basic-bls-signing.yml, .github/workflows/examples-basic-ibe.yml, .github/workflows/examples-basic-timelock-ibe.yml, .github/workflows/examples-password-manager.yml, examples/basic_bls_signing/frontend/package-lock.json, examples/basic_bls_signing/frontend/package.json, examples/basic_ibe/frontend/package-lock.json, examples/basic_ibe/frontend/package.json, examples/password_manager/frontend/package-lock.json, examples/password_manager/frontend/package.json, examples/password_manager_with_metadata/frontend/.prettierrc, examples/password_manager_with_metadata/frontend/package-lock.json, examples/password_manager_with_metadata/frontend/package.json
The workflows for testing examples installed frontend dependencies from the root of the repository, which is more than the dependencies of the examples. Therefore, CI was green if an example was missing a dependency but it was included in the root `package.json`. This PR fixes this logic and adds missing dependencies.
=> fix: dev dependencies in examples' frontends

backend/rs/ic_vetkeys/src/utils/mod.rs, backend/rs/ic_vetkeys/tests/utils.rs
Other interfaces including the management canister use VetKDKeyId to identify which VetKD master key to use. Use this type also for looking up hardcoded production keys instead of the one-off MasterPublicKeyId enum.
=> feat: Use VetKDKeyId instead of MasterPublicKeyId

backend/rs/ic_vetkeys/CHANGELOG.md, backend/rs/ic_vetkeys/README.md
Mention MSRV in the README
Mention VrfOutput being added
Fix incorrect references in the CHANGELOG
=> chore: Update README and CHANELOG for ic_vetkeys

Cargo.lock, Cargo.toml, backend/rs/ic_vetkeys/CHANGELOG.md, backend/rs/ic_vetkeys/Cargo.toml, backend/rs/ic_vetkeys/src/encrypted_maps/mod.rs, backend/rs/ic_vetkeys/src/key_manager/mod.rs, backend/rs/ic_vetkeys/src/types.rs
The main goal is to bump `ic-stable-structures` that introduce performance improvements and some breaking changes. Why should we bump it? Well, if we want to use the latest version of that crate in a canister, we will also need to have it in `ic-vetkeys` because we need it there for `KeyManager` and `EncryptedMaps`.
Also removes 2 unused deps in `ic-vetkeys`.
=> chore: bump Rust backend deps

.github/workflows/examples-encrypted-notes-dapp.yml, examples/encrypted_notes_dapp_vetkd/motoko/backend/main.mo, examples/encrypted_notes_dapp_vetkd/motoko/dfx.json, examples/encrypted_notes_dapp_vetkd/rust/dfx.json
Adapts the encrypted_notes_dapp example so that it works again with ICP Ninja, which recently upgraded to DFX 0.29.1, which ships with a new motoko compiler (0.16.1). The necessary changes for this were
* Declaring the actor as `persistent`
* Marking all transient variables explicitly as transient, and removing the redundant stable keywords.
Note that the example still uses the old way to persist data across updates, which is serialize/deserialize data in the preupgrade and postupgrade methods.
The Github workflow sets the `DFX_VERSION` environment variable, so that only this example uses the new DFX version 0.29.1. This also required to change the bind host from `localhost` to `127.0.0.1` as otherwise this new DFX version hits the following error:
```
Error: The replica returned an HTTP …
```
=> fix(crypto): encrypted_notes example: use persistent actor

.github/workflows/examples-password-manager-with-metadata.yml, .github/workflows/examples-password-manager.yml, backend/mo/canisters/ic_vetkeys_encrypted_maps_canister/mops.toml, backend/mo/canisters/ic_vetkeys_encrypted_maps_canister/src/Main.mo, examples/password_manager/motoko/mops.toml, examples/password_manager_with_metadata/motoko/backend/src/Main.mo, examples/password_manager_with_metadata/motoko/dfx.json, examples/password_manager_with_metadata/motoko/mops.toml, examples/password_manager_with_metadata/rust/dfx.json
Adapts the password_manager and password_manager_with_metadata examples so that they work again with ICP Ninja, which recently upgraded to DFX 0.29.1, which ships with a new motoko compiler (0.16.1). The necessary changes for this were
* Declaring the actor as `persistent` and fixing the compiler issues
The Github workflow sets the `DFX_VERSION` environment variable, so that only this example uses the new DFX version 0.29.1. This also required to change the bind host from `localhost` to `127.0.0.1` as otherwise this new DFX version hits the following error:
```
Error: The replica returned an HTTP Error: Http Error: status 400 Bad Request, content type "text/plain; charset=utf-8", content: error: no_authority
details:
The request is missing the required authority information (e.g. 'Host' …
```
=> fix(crypto): password manager examples: use persistent actor
